import yaml
import os

def generate():
    # Adjust these paths if your file structure differs
    yaml_path = "assets.yaml" 
    output_path = "Android/app/src/main/cpp/assets_manifest.h"

    if not os.path.exists(yaml_path):
        print(f"Error: {yaml_path} not found. Ensure assets.yaml is in the project root.")
        return

    print(f"Parsing {yaml_path}...")
    with open(yaml_path, 'r') as f:
        data = yaml.safe_load(f)

    # We extract the 'files' list from the yaml
    files = data.get('files', [])

    with open(output_path, 'w') as f:
        f.write("// Auto-generated asset manifest from assets.yaml\n")
        f.write("// Do not edit this file manually.\n\n")
        f.write("#ifndef ASSETS_MANIFEST_H\n#define ASSETS_MANIFEST_H\n\n")
        f.write("#include <stdint.h>\n\n")
        
        f.write("struct AssetEntry {\n")
        f.write("    uint32_t uid;       // ROM Offset\n")
        f.write("    uint32_t size;      // Length in bytes\n")
        f.write("    const char* name;   // Asset Identifier\n")
        f.write("    const char* type;   // Asset Type (e.g., SPRITE, MODEL)\n")
        f.write("};\n\n")
        
        f.write(f"static const int g_assets_count = {len(files)};\n\n")
        f.write("static const AssetEntry g_assets_manifest[] = {\n")
        
        for entry in files:
            uid = entry.get('uid', 0)
            size = entry.get('size', 0)
            name = entry.get('name', 'unknown')
            atype = entry.get('type', 'DATA')
            
            # Escape quotes in names/types if they exist
            f.write(f'    {{ {uid}, {size}, "{name}", "{atype}" }},\n')
            
        f.write("};\n\n")
        f.write("#endif // ASSETS_MANIFEST_H\n")

    print(f"Successfully generated {output_path} with {len(files)} entries.")

if __name__ == "__main__":
    generate()
