#!/usr/bin/env python3
import os
import re
from pathlib import Path

"""
SourceHarmonizer v75.33 — Submodule Target Realignment
═══════════════════════════════════════════════════════════════════════════════
LOG 62 — FileNotFoundError.
Redirected indexing to 'decomp-files/src' to match the submodule layout.
═══════════════════════════════════════════════════════════════════════════════
"""

class SourceHarmonizerV7533:
    def __init__(self):
        self.root = Path(os.getcwd())
        # Target the submodule directory specifically
        self.target_dir = self.root / "decomp-files"
        self.function_map = {} 
        self.stats = {"signatures_mapped": 0, "files_cleaned": 0}

    def verify_paths(self):
        print(f"[>] Root: {self.root}")
        print(f"[>] Target: {self.target_dir}")
        if not (self.target_dir / "src").exists():
            print(f"[!] Error: Could not find {self.target_dir}/src")
            print("[>] Ensure submodules are initialized.")
            os._exit(1)

    def map_all_functions(self):
        print("[>] Indexing engine signatures...")
        # Pattern to catch: [Return] [Name]([Params]) {
        def_pat = re.compile(r'^([\w\s\*]+?)\b(func_[A-Z0-9_]+)\s*\(([^)]*)\)\s*\{', re.MULTILINE)
        
        # Scan the decomp-files/src directory recursively
        for file_path in (self.target_dir / "src").rglob('*.c'):
            try:
                content = file_path.read_text(encoding='utf-8', errors='ignore')
                for match in def_pat.finditer(content):
                    ret_type, name, params = match.groups()
                    # Clean type (remove static/inline for the global header)
                    ret_type = " ".join(ret_type.split()).replace("static ", "").replace("inline ", "")
                    self.function_map[name] = f"extern {ret_type} {name}({params.strip()});"
            except Exception:
                continue
        
        self.stats["signatures_mapped"] = len(self.function_map)

    def generate_truth_header(self):
        # We place the generated header in the engine's include folder
        include_dir = self.target_dir / "include"
        include_dir.mkdir(parents=True, exist_ok=True)
        
        header_path = include_dir / "sh_signatures.h"
        print(f"[>] Writing {len(self.function_map)} signatures to {header_path}...")
        
        content = "#ifndef SH_SIGNATURES_H\n#define SH_SIGNATURES_H\n\n"
        content += "// Generated by SH v75.33\n\n"
        unique_sigs = sorted(list(set(self.function_map.values())))
        for sig in unique_sigs:
            content += sig + "\n"
        content += "\n#endif\n"
        
        header_path.write_text(content, encoding='utf-8')

    def run(self):
        self.verify_paths()
        self.map_all_functions()
        if self.stats["signatures_mapped"] > 0:
            self.generate_truth_header()
            print(f"\n[+] v75.33 Harmonization Complete.")
        else:
            print("[!] No functions found to map. Linker errors likely.")

if __name__ == "__main__":
    SourceHarmonizerV7533().run()
