#!/usr/bin/env python3
import os
import re
from pathlib import Path

"""
SourceHarmonizer v75.34 — Path Logic Robustness
═══════════════════════════════════════════════════════════════════════════════
LOG 65 — Fixed AttributeError on 'rglob' by standardizing Path traversal.
═══════════════════════════════════════════════════════════════════════════════
"""

class SourceHarmonizerV7534:
    def __init__(self):
        self.root = Path(os.getcwd()).resolve()
        # Explicitly build the path to the submodule src
        self.src_path = self.root / "decomp-files" / "src"
        self.function_map = {} 

    def verify_paths(self):
        print(f"[>] Root: {self.root}")
        print(f"[>] Searching in: {self.src_path}")
        if not self.src_path.exists():
            print(f"[!] Error: Path does not exist: {self.src_path}")
            # List directory to help debug if it fails again
            if self.src_path.parent.exists():
                print(f"[i] Parent directory contains: {os.listdir(self.src_path.parent)}")
            os._exit(1)

    def map_all_functions(self):
        print("[>] Indexing engine signatures...")
        def_pat = re.compile(r'^([\w\s\*]+?)\b(func_[A-Z0-9_]+)\s*\(([^)]*)\)\s*\{', re.MULTILINE)
        
        # Using os.walk for maximum compatibility across Python versions
        for root, dirs, files in os.walk(str(self.src_path)):
            for file in files:
                if file.endswith('.c'):
                    file_path = Path(root) / file
                    try:
                        content = file_path.read_text(encoding='utf-8', errors='ignore')
                        for match in def_pat.finditer(content):
                            ret_type, name, params = match.groups()
                            ret_type = " ".join(ret_type.split()).replace("static ", "").replace("inline ", "")
                            self.function_map[name] = f"extern {ret_type} {name}({params.strip()});"
                    except Exception as e:
                        print(f"[!] Warning: Could not read {file}: {e}")
                        continue

    def generate_truth_header(self):
        include_dir = self.root / "decomp-files" / "include"
        include_dir.mkdir(parents=True, exist_ok=True)
        header_path = include_dir / "sh_signatures.h"
        
        content = "#ifndef SH_SIGNATURES_H\n#define SH_SIGNATURES_H\n\n"
        content += "// Generated by SH v75.34\n\n"
        unique_sigs = sorted(list(set(self.function_map.values())))
        for sig in unique_sigs:
            content += sig + "\n"
        content += "\n#endif\n"
        header_path.write_text(content, encoding='utf-8')

    def run(self):
        self.verify_paths()
        self.map_all_functions()
        if self.function_map:
            self.generate_truth_header()
            print(f"\n[+] v75.34 Harmonization Complete. {len(self.function_map)} functions indexed.")
        else:
            print("[!] No functions found in the source directory.")

if __name__ == "__main__":
    SourceHarmonizerV7534().run()
