#include <jni.h>
#include <android/asset_manager.h>
#include <android/asset_manager_jni.h>
#include <android/log.h>
#include <stdint.h>

#define LOG_TAG "BKA_NATIVE"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)

extern "C" {
    // Verified symbols found in decomp-files/src/core1/code_0.c
    // and Android/app/src/main/cpp/emulator/resource_mgr.cpp
    void mainLoop(void); 
    void ResourceMgr_Init(const char* otrPath, uint8_t* manifestBuf, uint32_t manifestSize);
}

extern "C" {

JNIEXPORT void JNICALL
Java_com_bkawrapper_NativeBridge_nativeGameBoot(JNIEnv* env, jclass clazz, jstring otrPath, jobject assetManager) {
    LOGI("Initializing Banjo-Kazooie Native Engine...");

    const char* cOtrPath = env->GetStringUTFChars(otrPath, nullptr);
    AAssetManager* mgr = AAssetManager_fromJava(env, assetManager);

    // Load the binary manifest generated by generate_assets_header.py
    AAsset* asset = AAssetManager_open(mgr, "manifest_us.bin", AASSET_MODE_BUFFER);
    if (asset) {
        uint8_t* buffer = (uint8_t*)AAsset_getBuffer(asset);
        uint32_t size = AAsset_getLength(asset);
        
        LOGI("Manifest loaded: %u bytes. Initializing Resource Manager...", size);
        ResourceMgr_Init(cOtrPath, buffer, size);
        
        AAsset_close(asset);
    } else {
        __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, "FAILED TO LOAD MANIFEST_US.BIN");
    }

    // Launch the game entry point using the verified engine symbol
    LOGI("Starting Engine mainLoop...");
    mainLoop();

    env->ReleaseStringUTFChars(otrPath, cOtrPath);
}

JNIEXPORT void JNICALL
Java_com_bkawrapper_NativeBridge_nativeUpdate(JNIEnv* env, jclass clazz) {
    // Future implementation: hook into the engine's frame-update logic
}

}
