#include "assets_manifest.h" // Generated by the workflow
#include <android/log.h>

void process_rom_native(int fd) {
    // Now you have access to g_assets_manifest and g_assets_count
    for (int i = 0; i < g_assets_count; i++) {
        uint32_t offset = g_assets_manifest[i].uid;
        const char* name = g_assets_manifest[i].name;
        
        __android_log_print(ANDROID_LOG_INFO, "BKA", "Processing %s at offset 0x%X", name, offset);
        
        // Use pread() with the fd and offset to extract data without moving the file pointer
    }
}
