// File: Android/app/src/main/cpp/setintmask.cpp

#include <cstdint>
#include <array>

// ---- Interrupt mask constants (from N64 SDK) ----
constexpr uint16_t CLR_SP = 0x0001;
constexpr uint16_t SET_SP = 0x0002;
constexpr uint16_t CLR_SI = 0x0004;
constexpr uint16_t SET_SI = 0x0008;
constexpr uint16_t CLR_AI = 0x0010;
constexpr uint16_t SET_AI = 0x0020;
constexpr uint16_t CLR_VI = 0x0040;
constexpr uint16_t SET_VI = 0x0080;
constexpr uint16_t CLR_PI = 0x0100;
constexpr uint16_t SET_PI = 0x0200;
constexpr uint16_t CLR_DP = 0x0400;
constexpr uint16_t SET_DP = 0x0800;

constexpr uint16_t MI_INTR_MASK = 0x3F;

// ---- LUT matching __osRcpImTable ----
static constexpr std::array<uint16_t, 64> osRcpImTable = {{
    CLR_SP|CLR_SI|CLR_AI|CLR_VI|CLR_PI|CLR_DP,
    SET_SP|CLR_SI|CLR_AI|CLR_VI|CLR_PI|CLR_DP,
    CLR_SP|SET_SI|CLR_AI|CLR_VI|CLR_PI|CLR_DP,
    SET_SP|SET_SI|CLR_AI|CLR_VI|CLR_PI|CLR_DP,
    CLR_SP|CLR_SI|SET_AI|CLR_VI|CLR_PI|CLR_DP,
    SET_SP|CLR_SI|SET_AI|CLR_VI|CLR_PI|CLR_DP,
    CLR_SP|SET_SI|SET_AI|CLR_VI|CLR_PI|CLR_DP,
    SET_SP|SET_SI|SET_AI|CLR_VI|CLR_PI|CLR_DP,
    CLR_SP|CLR_SI|CLR_AI|SET_VI|CLR_PI|CLR_DP,
    SET_SP|CLR_SI|CLR_AI|SET_VI|CLR_PI|CLR_DP,
    CLR_SP|SET_SI|CLR_AI|SET_VI|CLR_PI|CLR_DP,
    SET_SP|SET_SI|CLR_AI|SET_VI|CLR_PI|CLR_DP,
    CLR_SP|CLR_SI|SET_AI|SET_VI|CLR_PI|CLR_DP,
    SET_SP|CLR_SI|SET_AI|SET_VI|CLR_PI|CLR_DP,
    CLR_SP|SET_SI|SET_AI|SET_VI|CLR_PI|CLR_DP,
    SET_SP|SET_SI|SET_AI|SET_VI|CLR_PI|CLR_DP,
    CLR_SP|CLR_SI|CLR_AI|CLR_VI|SET_PI|CLR_DP,
    SET_SP|CLR_SI|CLR_AI|CLR_VI|SET_PI|CLR_DP,
    CLR_SP|SET_SI|CLR_AI|CLR_VI|SET_PI|CLR_DP,
    SET_SP|SET_SI|CLR_AI|CLR_VI|SET_PI|CLR_DP,
    CLR_SP|CLR_SI|SET_AI|CLR_VI|SET_PI|CLR_DP,
    SET_SP|CLR_SI|SET_AI|CLR_VI|SET_PI|CLR_DP,
    CLR_SP|SET_SI|SET_AI|CLR_VI|SET_PI|CLR_DP,
    SET_SP|SET_SI|SET_AI|CLR_VI|SET_PI|CLR_DP,
    CLR_SP|CLR_SI|CLR_AI|SET_VI|SET_PI|CLR_DP,
    SET_SP|CLR_SI|CLR_AI|SET_VI|SET_PI|CLR_DP,
    CLR_SP|SET_SI|CLR_AI|SET_VI|SET_PI|CLR_DP,
    SET_SP|SET_SI|CLR_AI|SET_VI|SET_PI|CLR_DP,
    CLR_SP|CLR_SI|SET_AI|SET_VI|SET_PI|CLR_DP,
    SET_SP|CLR_SI|SET_AI|SET_VI|SET_PI|CLR_DP,
    CLR_SP|SET_SI|SET_AI|SET_VI|SET_PI|CLR_DP,
    SET_SP|SET_SI|SET_AI|SET_VI|SET_PI|CLR_DP,
    CLR_SP|CLR_SI|CLR_AI|CLR_VI|CLR_PI|SET_DP,
    SET_SP|CLR_SI|CLR_AI|CLR_VI|CLR_PI|SET_DP,
    CLR_SP|SET_SI|CLR_AI|CLR_VI|CLR_PI|SET_DP,
    SET_SP|SET_SI|CLR_AI|CLR_VI|CLR_PI|SET_DP,
    CLR_SP|CLR_SI|SET_AI|CLR_VI|CLR_PI|SET_DP,
    SET_SP|CLR_SI|SET_AI|CLR_VI|CLR_PI|SET_DP,
    CLR_SP|SET_SI|SET_AI|CLR_VI|CLR_PI|SET_DP,
    SET_SP|SET_SI|SET_AI|CLR_VI|CLR_PI|SET_DP,
    CLR_SP|CLR_SI|CLR_AI|SET_VI|CLR_PI|SET_DP,
    SET_SP|CLR_SI|CLR_AI|SET_VI|CLR_PI|SET_DP,
    CLR_SP|SET_SI|CLR_AI|SET_VI|CLR_PI|SET_DP,
    SET_SP|SET_SI|CLR_AI|SET_VI|CLR_PI|SET_DP,
    CLR_SP|CLR_SI|SET_AI|SET_VI|CLR_PI|SET_DP,
    SET_SP|CLR_SI|SET_AI|SET_VI|CLR_PI|SET_DP,
    CLR_SP|SET_SI|SET_AI|SET_VI|CLR_PI|SET_DP,
    SET_SP|SET_SI|SET_AI|SET_VI|CLR_PI|SET_DP,
    CLR_SP|CLR_SI|CLR_AI|CLR_VI|SET_PI|SET_DP,
    SET_SP|CLR_SI|CLR_AI|CLR_VI|SET_PI|SET_DP,
    CLR_SP|SET_SI|CLR_AI|CLR_VI|SET_PI|SET_DP,
    SET_SP|SET_SI|CLR_AI|CLR_VI|SET_PI|SET_DP,
    CLR_SP|CLR_SI|SET_AI|CLR_VI|SET_PI|SET_DP,
    SET_SP|CLR_SI|SET_AI|CLR_VI|SET_PI|SET_DP,
    CLR_SP|SET_SI|SET_AI|CLR_VI|SET_PI|SET_DP,
    SET_SP|SET_SI|SET_AI|CLR_VI|SET_PI|SET_DP,
    CLR_SP|CLR_SI|CLR_AI|SET_VI|SET_PI|SET_DP,
    SET_SP|CLR_SI|CLR_AI|SET_VI|SET_PI|SET_DP,
    CLR_SP|SET_SI|CLR_AI|SET_VI|SET_PI|SET_DP,
    SET_SP|SET_SI|CLR_AI|SET_VI|SET_PI|SET_DP,
    CLR_SP|CLR_SI|SET_AI|SET_VI|SET_PI|SET_DP,
    SET_SP|CLR_SI|SET_AI|SET_VI|SET_PI|SET_DP,
    CLR_SP|SET_SI|SET_AI|SET_VI|SET_PI|SET_DP,
    SET_SP|SET_SI|SET_AI|SET_VI|SET_PI|SET_DP
}};

// ---- Emulated global state ----
static uint32_t __OSGlobalIntMask = 0;
static uint16_t MI_INTR_MASK_REG_EMU = 0;

extern "C" uint32_t osSetIntMask(uint32_t mask)
{
    // Emulate CP0 Status read
    uint32_t oldStatus = 0;
    uint32_t oldMask   = __OSGlobalIntMask;

    // Compute LUT index exactly like the assembly
    uint32_t t0 = (mask & MI_INTR_MASK) & oldMask;
    uint32_t index = (t0 >> 15) & 0x3F;

    // Write emulated MI interrupt mask register
    MI_INTR_MASK_REG_EMU = osRcpImTable[index];

    // Preserve CP0 status bits (0xFF01 logic)
    uint32_t merged =
        (oldStatus & 0xFFFF00FF) |
        ((mask & 0xFF01) & (oldMask & 0xFF00));

    __OSGlobalIntMask = mask;
    return oldStatus;
}